### ISSUE TITLE
Version 0.5.0 not published to NPM

### ISSUE THREAD

**Issue by tpaulus** [lunch-money/lunch-money-js#6]
Hi there,

Could we get the latest version of the SDK published to NPM as it was last published 2 years ago and is stuck on V 0.0.1?
https://www.npmjs.com/package/lunch-money

Thanks!

**Comment by iloveitaly** [comment]
We have been trying to get NPM to assign ownership to us. Do you know how
to get in touch with someone at NPM to transfer ownership to the LM owner?
I've tried a couple channels and nothing has worked.

**Comment by tpaulus** [comment]
@joehoyle is the owner of the package. Can they help us?

**Comment by iloveitaly** [comment]
finally got access and published!
